Fix cancelAllOrders compile error.
Make the args argument required, but make its product_id property
optional, so it's still easy to not set it.

index.d.ts(225,56): error TS1016: A required parameter cannot follow an optional parameter.